import { Employee } from './EmployeeGoalsTable';

// Mock data for employees across different divisions
export const mockEmployees: Employee[] = [
  {
    id: 1,
    name: 'Alex Johnson',
    division: 'Sales',
    position: 'Senior Sales Executive',
    avatar: '👨‍💼',
    image: '/avatars/alex.jpg',
    goalsCompleted: 42,
    goalsInProgress: 3,
    totalPoints: 2450,
    lastGoalAchieved: '2 days ago'
  },
  {
    id: 2,
    name: 'Sarah Williams',
    division: 'Sales',
    position: 'Sales Team Lead',
    avatar: '👩‍💼',
    image: '/avatars/sarah.jpg',
    goalsCompleted: 38,
    goalsInProgress: 2,
    totalPoints: 2280,
    lastGoalAchieved: '1 week ago'
  },
  {
    id: 3,
    name: 'Michael Brown',
    division: 'Marketing',
    position: 'Marketing Manager',
    avatar: '👨‍💼',
    image: '/avatars/michael.jpg',
    goalsCompleted: 35,
    goalsInProgress: 4,
    totalPoints: 2150,
    lastGoalAchieved: '3 days ago'
  },
  {
    id: 4,
    name: 'Emma Davis',
    division: 'Sales',
    position: 'Junior Sales Executive',
    avatar: '👩‍💼',
    image: '/avatars/emma.jpg',
    goalsCompleted: 32,
    goalsInProgress: 2,
    totalPoints: 1980,
    lastGoalAchieved: '5 days ago'
  },
  {
    id: 5,
    name: 'David Chen',
    division: 'Listing Support',
    position: 'Listing Manager',
    avatar: '👨‍💼',
    image: '/avatars/david.jpg',
    goalsCompleted: 30,
    goalsInProgress: 1,
    totalPoints: 1850,
    lastGoalAchieved: '1 day ago'
  },
  {
    id: 6,
    name: 'Lisa Taylor',
    division: 'Admin',
    position: 'Administrative Director',
    avatar: '👩‍💼',
    image: '/placeholder.svg',
    goalsCompleted: 28,
    goalsInProgress: 3,
    totalPoints: 1720,
    lastGoalAchieved: '2 weeks ago'
  },
  {
    id: 7,
    name: 'James Wilson',
    division: 'Operations',
    position: 'Operations Manager',
    avatar: '👨‍💼',
    image: '/placeholder.svg',
    goalsCompleted: 26,
    goalsInProgress: 2,
    totalPoints: 1590,
    lastGoalAchieved: '1 week ago'
  },
  {
    id: 8,
    name: 'Olivia Martin',
    division: 'Sales',
    position: 'Sales Executive',
    avatar: '👩‍💼',
    image: '/placeholder.svg',
    goalsCompleted: 24,
    goalsInProgress: 3,
    totalPoints: 1480,
    lastGoalAchieved: '3 days ago'
  },
  {
    id: 9,
    name: 'Daniel Lee',
    division: 'IT',
    position: 'IT Manager',
    avatar: '👨‍💼',
    image: '/placeholder.svg',
    goalsCompleted: 22,
    goalsInProgress: 1,
    totalPoints: 1350,
    lastGoalAchieved: '4 days ago'
  },
  {
    id: 10,
    name: 'Sophia Garcia',
    division: 'HR',
    position: 'HR Director',
    avatar: '👩‍💼',
    image: '/placeholder.svg',
    goalsCompleted: 20,
    goalsInProgress: 2,
    totalPoints: 1240,
    lastGoalAchieved: '1 week ago'
  },
  {
    id: 11,
    name: 'Ryan Murphy',
    division: 'Finance',
    position: 'Financial Analyst',
    avatar: '👨‍💼',
    image: '/placeholder.svg',
    goalsCompleted: 18,
    goalsInProgress: 2,
    totalPoints: 1120,
    lastGoalAchieved: '2 weeks ago'
  },
  {
    id: 12,
    name: 'Isabella Lopez',
    division: 'Marketing',
    position: 'Digital Marketing Specialist',
    avatar: '👩‍💼',
    image: '/placeholder.svg',
    goalsCompleted: 16,
    goalsInProgress: 3,
    totalPoints: 980,
    lastGoalAchieved: '1 month ago'
  },
  {
    id: 13,
    name: 'Ethan Thompson',
    division: 'Sales',
    position: 'Sales Executive',
    avatar: '👨‍💼',
    image: '/placeholder.svg',
    goalsCompleted: 15,
    goalsInProgress: 1,
    totalPoints: 920,
    lastGoalAchieved: '3 weeks ago'
  },
  {
    id: 14,
    name: 'Ava Mitchell',
    division: 'Customer Support',
    position: 'Support Team Lead',
    avatar: '👩‍💼',
    image: '/placeholder.svg',
    goalsCompleted: 14,
    goalsInProgress: 2,
    totalPoints: 860,
    lastGoalAchieved: '2 weeks ago'
  },
  {
    id: 15,
    name: 'Noah Anderson',
    division: 'Listing Support',
    position: 'Listing Coordinator',
    avatar: '👨‍💼',
    image: '/placeholder.svg',
    goalsCompleted: 12,
    goalsInProgress: 1,
    totalPoints: 740,
    lastGoalAchieved: '1 month ago'
  }
]; 