import { Goal } from './GoalCard';

// Mock goals for employee with ID 1 (Alex Johnson)
export const mockEmployeeGoals: Record<number, Goal[]> = {
  1: [
    {
      id: 101,
      title: "Achieve $6M in Sales",
      type: "personal",
      goalType: "target-revenue",
      timelineType: "quarterly",
      timelinePeriod: "2023-Q4",
      description: "Reach $6 million in total sales volume by the end of Q4.",
      target: "6,000,000",
      current: "5,400,000",
      deadline: "Dec 31, 2023",
      progress: 90,
      reward: "6% Bonus Commission",
      icon: "target",
      iconColor: "blue",
      milestones: [
        { value: 25, label: "25%", reached: true },
        { value: 50, label: "50%", reached: true },
        { value: 75, label: "75%", reached: true },
        { value: 100, label: "100%", reached: false },
      ],
      createdAt: "Oct 1, 2023"
    },
    {
      id: 102,
      title: "12 New Listings",
      type: "personal",
      goalType: "kpi",
      timelineType: "monthly",
      timelinePeriod: "2023-12",
      description: "Acquire 12 new property listings in the luxury market segment.",
      target: "12",
      current: "8",
      deadline: "Dec 31, 2023",
      progress: 67,
      reward: "Marketing Budget Increase",
      icon: "home",
      iconColor: "green",
      milestones: [
        { value: 25, label: "25%", reached: true },
        { value: 50, label: "50%", reached: true },
        { value: 75, label: "75%", reached: false },
        { value: 100, label: "100%", reached: false },
      ],
      createdAt: "Dec 1, 2023"
    },
    {
      id: 103,
      title: "Client Satisfaction",
      type: "personal",
      goalType: "kpi",
      timelineType: "annually",
      timelinePeriod: "2023",
      description: "Maintain a 95% client satisfaction rating across all transactions.",
      target: "95",
      current: "95",
      deadline: "Dec 31, 2023",
      progress: 100,
      reward: "Recognition Award",
      icon: "star",
      iconColor: "amber",
      milestones: [
        { value: 25, label: "25%", reached: true },
        { value: 50, label: "50%", reached: true },
        { value: 75, label: "75%", reached: true },
        { value: 100, label: "100%", reached: true },
      ],
      createdAt: "Jan 5, 2023"
    },
    {
      id: 104,
      title: "Team Collaboration",
      type: "team",
      goalType: "custom",
      timelineType: "quarterly",
      timelinePeriod: "2023-Q4",
      description: "Lead team initiatives and improve cross-department collaboration.",
      target: "100",
      current: "100",
      deadline: "Dec 31, 2023",
      progress: 100,
      reward: "Leadership Recognition",
      icon: "users",
      iconColor: "purple",
      milestones: [
        { value: 25, label: "25%", reached: true },
        { value: 50, label: "50%", reached: true },
        { value: 75, label: "75%", reached: true },
        { value: 100, label: "100%", reached: true },
      ],
      createdAt: "Oct 1, 2023",
      teamMembers: [
        { id: 1, name: "Alex", avatar: "/avatars/alex.jpg" },
        { id: 2, name: "Sarah", avatar: "/avatars/sarah.jpg" },
      ]
    }
  ],
  2: [
    {
      id: 201,
      title: "Team Sales Target",
      type: "team",
      goalType: "target-revenue",
      timelineType: "quarterly",
      timelinePeriod: "2023-Q4",
      description: "Lead team to achieve $10 million in sales volume for Q4.",
      target: "10,000,000",
      current: "8,500,000",
      deadline: "Dec 31, 2023",
      progress: 85,
      reward: "Team Retreat",
      icon: "users",
      iconColor: "purple",
      milestones: [
        { value: 25, label: "25%", reached: true },
        { value: 50, label: "50%", reached: true },
        { value: 75, label: "75%", reached: true },
        { value: 100, label: "100%", reached: false },
      ],
      createdAt: "Oct 1, 2023",
      teamMembers: [
        { id: 2, name: "Sarah", avatar: "/avatars/sarah.jpg" },
        { id: 4, name: "Emma", avatar: "/avatars/emma.jpg" },
        { id: 8, name: "Olivia", avatar: "/placeholder.svg" },
      ]
    },
    {
      id: 202,
      title: "Mentorship Program",
      type: "personal",
      goalType: "custom",
      timelineType: "annually",
      timelinePeriod: "2023",
      description: "Mentor 5 junior sales executives to improve their performance.",
      target: "5",
      current: "5",
      deadline: "Dec 31, 2023",
      progress: 100,
      reward: "Leadership Award",
      icon: "graduation-cap",
      iconColor: "blue",
      milestones: [
        { value: 25, label: "25%", reached: true },
        { value: 50, label: "50%", reached: true },
        { value: 75, label: "75%", reached: true },
        { value: 100, label: "100%", reached: true },
      ],
      createdAt: "Jan 15, 2023"
    }
  ],
  3: [
    {
      id: 301,
      title: "Marketing Campaign ROI",
      type: "personal",
      goalType: "kpi",
      timelineType: "quarterly",
      timelinePeriod: "2023-Q4",
      description: "Achieve 300% ROI on marketing campaigns for Q4.",
      target: "300",
      current: "275",
      deadline: "Dec 31, 2023",
      progress: 92,
      reward: "Budget Increase",
      icon: "trending-up",
      iconColor: "green",
      milestones: [
        { value: 25, label: "25%", reached: true },
        { value: 50, label: "50%", reached: true },
        { value: 75, label: "75%", reached: true },
        { value: 100, label: "100%", reached: false },
      ],
      createdAt: "Oct 1, 2023"
    },
    {
      id: 302,
      title: "Social Media Growth",
      type: "personal",
      goalType: "kpi",
      timelineType: "monthly",
      timelinePeriod: "2023-12",
      description: "Increase social media engagement by 50% in December.",
      target: "50",
      current: "35",
      deadline: "Dec 31, 2023",
      progress: 70,
      reward: "Professional Development Course",
      icon: "share",
      iconColor: "blue",
      milestones: [
        { value: 25, label: "25%", reached: true },
        { value: 50, label: "50%", reached: true },
        { value: 75, label: "75%", reached: false },
        { value: 100, label: "100%", reached: false },
      ],
      createdAt: "Dec 1, 2023"
    }
  ]
}; 